import React, { Component } from "react";
import { Text, StyleSheet } from "react-native";

export default class ScrambledText extends Component {
  constructor(props) {
    super(props);
  }
  fillInBox(letter, solutionBox) {
    solutionBox = solutionBox.split(" ");
    let newWord = "";
    let newSolution = "";
    let wordBox = solutionBox[letter.wordIdx];
    for (let i = 0; i < wordBox.length; i++) {
      // first, look for index of solutionBox that matches index of letter's word
      if (wordBox[i] == "_") {
        newWord = wordBox.replace(wordBox[i], letter.letter);
      }
    }
    // this isn't working because solutionBox needs to be an array first. It needs to be generated by copying the scrambled string and replacing each non ' ' with '_'
    solutionBox.splice(letter.wordIdx, 1, newWord);
    newSolution = solutionBox.join(" ");
    console.log(newSolution);
    this.props.callback(newSolution, letter);
  }
  render() {
    return (
      // eslint-disable-next-line react/react-in-jsx-scope
      <Text
        style={styles.scrambledText}
        key={this.props.props.idx}
        // eslint-disable-next-line no-loop-func
        onPress={() =>
          this.fillInBox(this.props.props, this.props.props.solutionBox)
        }
      >
        {this.props.props.letter}
      </Text>
    );
  }
}

const styles = StyleSheet.create({
  scrambledText: {
    fontSize: 40,
    color: "whitesmoke",
    lineHeight: 60,
    textAlign: "center"
  },
  chosenLetters: {
    fontSize: 40,
    color: "blue",
    lineHeight: 60,
    textAlign: "center"
  }
});
